Add initial project files
CloudNet-v2/v2-cloudflaresystem pull request #1
Opened 2019-11-08 19:02 UTC by MeinerLP1

These files were extracted from the main repository for the purpose of separate updating and maintaining.

2019-11-08 20:03 UTC, GiantTreeLP requested changes
Please also format the code

2019-11-08 20:03 UTC, GiantTreeLP commented on CloudFlareModule/pom.xml
> +                <artifactId>maven-assembly-plugin</artifactId>
why maven assembly and not shade?

2019-11-08 20:03 UTC, GiantTreeLP commented on CloudFlareModule/src/main/java/eu/cloudnetservice/cloudflare/module/ProjectMain.java
> +public final class ProjectMain extends CoreModule {
we have spoken about names already

2019-11-08 20:03 UTC, GiantTreeLP commented on CloudFlareModule/src/main/java/eu/cloudnetservice/cloudflare/module/ProjectMain.java
> +	private final ExecutorService executor = Executors.newSingleThreadExecutor();
Is another executor really necessary? The master does have it's own task scheduling built in.

2019-11-08 20:03 UTC, GiantTreeLP commented on CloudFlareModule/src/main/java/eu/cloudnetservice/cloudflare/module/listener/ProxyAddListener.java
> +				NetworkUtils.sleepUninterruptedly(500);
What even is the reason for this weird call?

2019-11-09 13:37 UTC, GiantTreeLP commented on CloudFlareModule/src/main/java/eu/cloudnetservice/cloudflare/module/ModuleMain.java
> +public final class ModuleMain extends CoreModule {
really?

2019-11-09 15:52 UTC, MeinerLP1 commented
I think is merge ready

2019-11-09 16:23 UTC, GiantTreeLP approved these changes

2019-11-09 16:23 UTC, merged